DROP TABLE aliases CASCADE;
DROP TABLE writer_types CASCADE;
DROP TABLE app_users CASCADE;
DROP TABLE applications CASCADE;
DROP TABLE contacts CASCADE;
DROP TABLE aliases_members CASCADE;
DROP TABLE messages CASCADE;
DROP TABLE attachments CASCADE;
DROP TABLE contacts_members CASCADE;
DROP TABLE imports CASCADE;
DROP FUNCTION FindRowNumber;
DROP FUNCTION DeleteMessagesWithImportId;
DROP FUNCTION DeleteEmptyContacts;