//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases can be created only from contacts (not other aliases).
        /// </summary>
        internal static string AliasCreation {
            get {
                return ResourceManager.GetString("AliasCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias with id {0} not found.
        /// </summary>
        internal static string AliasNotFound {
            get {
                return ResourceManager.GetString("AliasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User (you).
        /// </summary>
        internal static string app_user {
            get {
                return ResourceManager.GetString("app_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application {0} not found.
        /// </summary>
        internal static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from app user can not be also from a contact member.
        /// </summary>
        internal static string AppUserContactMember {
            get {
                return ResourceManager.GetString("AppUserContactMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment with id {0} not found.
        /// </summary>
        internal static string AttachmentNotFound {
            get {
                return ResourceManager.GetString("AttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with id {0} not found.
        /// </summary>
        internal static string ContactNotFound {
            get {
                return ResourceManager.GetString("ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts not found.
        /// </summary>
        internal static string ContactsNotFound {
            get {
                return ResourceManager.GetString("ContactsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only internal aliases name&apos;s can be edited.
        /// </summary>
        internal static string EditNotInernalAliasName {
            get {
                return ResourceManager.GetString("EditNotInernalAliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email exists.
        /// </summary>
        internal static string EmailConflict {
            get {
                return ResourceManager.GetString("EmailConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook username can&apos;t be empty.
        /// </summary>
        internal static string EmptyFacebookName {
            get {
                return ResourceManager.GetString("EmptyFacebookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty.
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be empty.
        /// </summary>
        internal static string EmptyUsername {
            get {
                return ResourceManager.GetString("EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Invalid file.
        /// </summary>
        internal static string Error_InvalidFile {
            get {
                return ResourceManager.GetString("Error_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - no messages.
        /// </summary>
        internal static string Error_NoMessages {
            get {
                return ResourceManager.GetString("Error_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Error_UnknownError {
            get {
                return ResourceManager.GetString("Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access for this alias.
        /// </summary>
        internal static string ForbiddenAlias {
            get {
                return ResourceManager.GetString("ForbiddenAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access for this attachment.
        /// </summary>
        internal static string ForbiddenAttachment {
            get {
                return ResourceManager.GetString("ForbiddenAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access for this contact.
        /// </summary>
        internal static string ForbiddenContact {
            get {
                return ResourceManager.GetString("ForbiddenContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access for this import.
        /// </summary>
        internal static string ForbiddenImport {
            get {
                return ResourceManager.GetString("ForbiddenImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t acces this resuorce.
        /// </summary>
        internal static string ForbiddenResource {
            get {
                return ResourceManager.GetString("ForbiddenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import with id: {0} not found.
        /// </summary>
        internal static string ImportNotFound {
            get {
                return ResourceManager.GetString("ImportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid alias name.
        /// </summary>
        internal static string InvalidAliasName {
            get {
                return ResourceManager.GetString("InvalidAliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import has invalid status. Should be {0} but was {1}.
        /// </summary>
        internal static string InvalidImportStatus {
            get {
                return ResourceManager.GetString("InvalidImportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameAndPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger.
        /// </summary>
        internal static string messenger {
            get {
                return ResourceManager.GetString("messenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact member is not a member of given contact.
        /// </summary>
        internal static string MissingContactMember {
            get {
                return ResourceManager.GetString("MissingContactMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw aliases can&apos;t be deleted.
        /// </summary>
        internal static string RawAliasDeletion {
            get {
                return ResourceManager.GetString("RawAliasDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw aliases can&apos;t be modified.
        /// </summary>
        internal static string RawAliasModification {
            get {
                return ResourceManager.GetString("RawAliasModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string sms {
            get {
                return ResourceManager.GetString("sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string StatusCreated {
            get {
                return ResourceManager.GetString("StatusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status {0} not found.
        /// </summary>
        internal static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string StatusQueued {
            get {
                return ResourceManager.GetString("StatusQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact InApplicationId can contain maximum of 256 characters.
        /// </summary>
        internal static string TooLongContactInApplicationId {
            get {
                return ResourceManager.GetString("TooLongContactInApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact member name can contain maximum of 256 characters.
        /// </summary>
        internal static string TooLongContactMemberName {
            get {
                return ResourceManager.GetString("TooLongContactMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name can contain maximum of 256 characters.
        /// </summary>
        internal static string TooLongContactName {
            get {
                return ResourceManager.GetString("TooLongContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook usernname can contain maximum of 256 characters.
        /// </summary>
        internal static string TooLongFacebookName {
            get {
                return ResourceManager.GetString("TooLongFacebookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content can contains maximum of 307200 characters.
        /// </summary>
        internal static string TooLongMessageContent {
            get {
                return ResourceManager.GetString("TooLongMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be longer than 20 characters..
        /// </summary>
        internal static string TooLongUsername {
            get {
                return ResourceManager.GetString("TooLongUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email: {0} not found.
        /// </summary>
        internal static string UserByEmail {
            get {
                return ResourceManager.GetString("UserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id: {0} not found.
        /// </summary>
        internal static string UserByIdNotFound {
            get {
                return ResourceManager.GetString("UserByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not found.
        /// </summary>
        internal static string UserByUsernameNotFound {
            get {
                return ResourceManager.GetString("UserByUsernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username exists.
        /// </summary>
        internal static string UsernameConflict {
            get {
                return ResourceManager.GetString("UsernameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in.
        /// </summary>
        internal static string UserNotLoggedInException {
            get {
                return ResourceManager.GetString("UserNotLoggedInException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer type {0} not found.
        /// </summary>
        internal static string WriterTypeNotFound {
            get {
                return ResourceManager.GetString("WriterTypeNotFound", resourceCulture);
            }
        }
    }
}
