DROP TABLE alias CASCADE;
DROP TABLE writer_type CASCADE;
DROP TABLE app_user CASCADE;
DROP TABLE application CASCADE;
DROP TABLE contact CASCADE;
DROP TABLE alias_member CASCADE;
DROP TABLE message CASCADE;