DROP TABLE aliases CASCADE;
DROP TABLE writer_types CASCADE;
DROP TABLE app_users CASCADE;
DROP TABLE applications CASCADE;
DROP TABLE contacts CASCADE;
DROP TABLE aliases_members CASCADE;
DROP TABLE messages CASCADE;
DROP TABLE attachments CASCADE;